blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://discord.gg/fVyRaUDgxW
    about: For general questions, join us on Discord
  - name: SDK issue (TypeScript)
    url: https://github.com/OpenRouterTeam/typescript-sdk/issues
    about: For issues with the TypeScript SDK
  - name: SDK issue (Python)
    url: https://github.com/OpenRouterTeam/python-sdk/issues
    about: For issues with the Python SDK
